fix: fixed functions and routes names (re-added a nextjs frontend for tests)

diff --git a/rapport/Dockerfile b/rapport/Dockerfile
--- a/rapport/Dockerfile
+++ b/rapport/Dockerfile
@@ -8,5 +8,11 @@ WORKDIR /app
 COPY src /app
 
 # Run pdflatex on the main LaTeX file
-RUN pdflatex main.tex
-RUN pdflatex main.tex
+RUN pdflatex -interaction=nonstopmode main.tex
+
+# Ensure that the main.aux file exists before running bibtex
+RUN test -f main.aux && bibtex main || echo "Skipping bibtex as main.aux not found"
+
+# Run pdflatex multiple times to resolve cross-references
+RUN pdflatex -interaction=nonstopmode main.tex
+RUN pdflatex -interaction=nonstopmode main.tex
